ginuerzh/gost

cmd/gost/main.go
ws.go

see #54 
gost.json example:
```json
{
"ChainNodes": [
"http+tls://server_ip:443"
],
"ServeNodes": [
":8080"
]
}
```
usage command:
<kbd>gost -C gost.json</kbd>

add configure file support

---

http.go

Without "Proxy-Authenticate" header, Proxy Authentication of http2 will not work correctly on chrome(With SwitchyOmega). Vendor should also be update soon.

add "Proxy-Authenticate" header for http2

---

chain.go
cmd/gost/main.go
conn.go
node.go
obfs4.go
server.go

This pull request wraps TOR's obfs4 plugin as a transport layer for gost. Gost could benefit from this feature since it makes the proxy more resistant to third parties' interference and active probing.
Configuration is through the query string with keys including cert, iat-mode, and state-dir (optional, default is current dir). When the server runs at the first time, cert is generated automatically and iat-mode is set to 0 if not specified otherwise. Then the client just need to copy and paste the URL from server's stdout.
To reset the server's profile (so that it can have a new packet length distribution), remove files starting with obfs in the state-dir.

support obfs4 transport

---

snapcraft.yaml

The snap was failing to build because it was using older version of go to build gost. This change makes sure that `go1.8.3` is built before `gost`, so it gets used in the build of gost.
The snap will still fail, but that seems to be a problem on master:
```
go build -o /home/ev/gost/parts/gost/go/bin/gost github.com/ginuerzh/gost/cmd/gost
go build -o /home/ev/gost/parts/gost/go/bin/bench github.com/ginuerzh/gost/examples/bench
github.com/ginuerzh/gost/examples/bench/srv.go:17: quiet redeclared in this block
previous declaration at github.com/ginuerzh/gost/examples/bench/cli.go:19
github.com/ginuerzh/gost/examples/bench/srv.go:33: main redeclared in this block
previous declaration at github.com/ginuerzh/gost/examples/bench/cli.go:38
```
Pinning to the most recent release tag of gost fixes …

Build gost after go1.8.3, so go 1.8.3 can be used in the build.

---

sni.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7c0555]
goroutine 84 [running]:
github.com/ginuerzh/gost.(*sniHandler).Handle(0xc42028d520, 0xb05340, 0xc42000e468)
/root/gopath/src/github.com/ginuerzh/gost/sni.go:65 +0x445
created by github.com/ginuerzh/gost.(*Server).Serve
/root/gopath/src/github.com/ginuerzh/gost/server.go:62 +0x145
exit status 2
```

fix panic error

---

http.go

need req.Body.Close() to avoid memory leaks

Fix http Handle

---

redirect_win.go

Fix Error:
```
.\redirect_win.go:25:2: cannot use h (type *tcpRedirectHandler) as type Handler in return argument:
*tcpRedirectHandler does not implement Handler (missing Init method)
```

fix build in go-1.10.3 at win

---

ss.go

If client connect without send any data(maybe wait for server,like mysql), it will not  create connection
cause is that cache.

Fix: ss: block if server send first(like mysql)

---

cmd/gost/main.go

Otherwise we can't get the gost version by this:
```shell
gost -V | cut -d' ' -f2
```
Only
```shell
gost -V 2>&1 | cut -d' ' -f2
```
can return the right version information.

Print version info to Stdout instead of Stderr

---

.github/workflows/buildx.yaml
Dockerfile
docker-compose.yaml

Go already can cross-build easily for other architectures, so using QEMU is quite a bit slower.
Here I've changed the Dockerfile to use the --platform arg for FROM and tell Go what ARCH to build for.
I've also switched the build to use `buildx bake` which will run all the builds in parallel.  Bake doesn't work directly with a Dockerfile, so I created a quick docker-compose.yaml file for it to use.
This builds all the images in about 2 minutes.
Also, there seems to be a bug with calling '${GITHUB_SHA::8}'  maybe you want to remove the ::8 but I didn't want to change it, not sure what it was there for.

Build go binaries without QEMU

---

README.md
README_en.md

Hi, @ginuerzh! I add a [pull request](https://github.com/Homebrew/homebrew-core/pull/62915) for `gost` to homebrew-core, and it has been accepted by the homebrew maintainers.
From now on, we can install `gost` on macOS with homebrew, or even on Linux with linuxbrew (maybe there is some delay).
```console
brew install gost
```

Add installation instructions for Homebrew

---

cmd/gost/route.go
tls.go

See https://github.com/ginuerzh/gost/issues/629#issuecomment-686485770
If the server doesn't have a domain, certificate pinning is invaluable for websocket. So I use a new way to verify the certificate, which is effective for both tls and websocket.

Certificate pinning for servers without domain

---

http.go

libcurl and some proxy application will keep sending authentication in
same connection if auth failed which is not supported.
fixes #583

Close connection if authentication failed

---

relay.go

noDelay=false时，会依次写入 Requset header , payload len, payload
noDelay=true时，Request错误的被当成了 payload写入，顺序为 payload len,Request Header
本PR修复上述问题。
Closes #663

Fix: relay udp forward

---

go.mod
go.sum
tuntap_linux.go

依赖的包名从 github.com/milosgajdos83/tenus 变成了 github.com/milosgajdos/tenus
另外 v0.0.3 包含了一处修复 https://github.com/milosgajdos/tenus/commit/4c07e9afd868e8a810d552ddba9ae4516ca64b9a
可以防止其他依赖 github.com/ginuerzh/gost 的包用 bazel 构建时的报错

bump github.com/milosgajdos/tenus to v0.0.3

---

tuntap_linux.go

```shell
naison@naison-virtual-machine:~$ sudo ip route add 10.10.0.0/16 dev tun0
[sudo] password for naison: 
naison@naison-virtual-machine:~$ sudo ip route add 10.10.0.0/16 dev tun0
RTNETLINK answers: File exists
naison@naison-virtual-machine:~$ 
```
Linux如果重复添加相同路由，会报错已经存在，window和macOS不会报这样的错误。因此这里加上忽略已经存在的路由。
```shell
2021/08/21 11:19:21 tuntap_linux.go:40: [tun] ip link set dev tun0 mtu 1350
2021/08/21 11:19:21 tuntap_linux.go:47: [tun] ip address add 223.254.254.2/24 dev tun0
2021/08/21 11:19:21 tuntap_linux.go:54: [tun] ip link set dev tun0 up
2021/08/21 11:19:21 tuntap_linux.go:151: [tun] ip route add 10.10.0.0/16 dev tun0
2021/08/21 11:19:21 main.go:88: ip route add 10.10.0.0/16 dev tun0: file exists
```

ignore linux error: File exists while add same route twice

---

chain.go
cmd/gost/main.go
cmd/gost/route.go
handler.go

Added an `-M <mark>` option to specify fwmark for outbound connections. It can also be set by config file.
```json
{
"Routes": [
{
"Retries": 3,
"ServeNodes": [
"quic://:443"
],
"Mark": 1000
}
]
}
```

Add -M option for Fwmark

---

chain.go
cmd/gost/main.go
cmd/gost/route.go
sockopts_linux.go
sockopts_other.go

允许绑定到指定的网卡（使用 `SO_BINDTODEVICE`）
修复了 `newRoute` 会创建一个新 `Chain` 导致 `Mark` 设定在出口的时候被忽略

允许绑定出口到指定网卡上

---

sockopts_other.go

To compatible with older Go version on some cloud environment , such as Google App Engine using 1.16

Compatible with older Go version

---

server.go

If the method returns before the second direction is done, the socket may be closed or the error ignored. Typically not a problem, in most cases when a direction is closed the other is also done, but for some protocols it may matter, and it seems 
the correct way to handle.

Wait for the second copy error

---

obfs.go

`obfs4Listener.Accept()` returns an error when obfs4 handshake fails, which in practice happens routinely when someone scans a machine that has an open listening port.
Currently the accept loop in server.go exits on first such error, which makes further connections to the same port impossible.
This change wraps obfs4 handshake errors into a custom error type that satisfies net.Error and presents itself as temporary, which will prevent such errors from aborting the server.
I think this is what was causing #243.

Do not exit the server loop on obfs4 connection errors

---

cmd/gost/peer.go
cmd/gost/route.go
selector.go
selector_test.go

新增特性: 支持peer节点测速并过滤出最快的n个节点
配置参考: 过滤出最快的8个节点 (参数值为0表示无需过滤)
```
fastest_count: 8
```

feat: support node sort by tcp ping latency

---

socks.go

(resending without an unnecessary file; cf. https://github.com/ginuerzh/gost/pull/1029)
Currently relay ports for SOCKS UDP associate are obtained with `nil` (`[::]:0`), and then replied to clients with the IP replaced by TCP local address.
My implementation uses the TCP local address instead of `nil` when getting UDP relay ports.
This solves possible problems in situations where the SOCKS server can be seen through more than one IP addresses.
For example, if we use some external interface address (like 10.0.0.1) to access gost SOCKS5 proxy running on the same machine as client, only my implementation will work, because current implementation will send back UDP packets using localhost (127.0.0.1), which is different from the replied relay port. 
Also, the current implementation typically …

use outgoing interface's IP for UDP relay port

---

.github/workflows/buildx.yaml

Tested on visionfive2
```
root@visionfive2-1:~/gost/cmd/gost# uname -a
Linux visionfive2-1 5.15.0-starfive #1 SMP Sun Jun 11 07:48:39 UTC 2023 riscv64 GNU/Linux
root@visionfive2-1:~/gost/cmd/gost# ./gost -V
gost 2.12.0 (go1.22.3 linux/riscv64)
```

chore: add riscv64 in buildx
